name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-releaser-nix-store-cache
      - nscloud-git-mirror-1gb
    steps:
      - uses: AtomiCloud/actions.setup-nix@v1.1.0
      - uses: AtomiCloud/actions.cache-npm@v1.0.0

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix develop .#releaser -c scripts/ci/release.sh
